services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: net8-sdk
    working_dir: /src
    volumes:
      - ./:/src
      - ~/.nuget/packages:/root/.nuget/packages
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8888
    ports:
      - "8888:8888"
    command: sleep infinity
    # Uncomment to avoid root-owned artifacts on Linux hosts
    # user: "${UID}:${GID}"

  # Optional: database examples
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=changeme
  #     - MYSQL_DATABASE=appdb
  #     - MYSQL_USER=app
  #     - MYSQL_PASSWORD=app123
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10

volumes:
  mysql_data:
